- app/controllers/ServiceProxy.scala
- test/controllers/ServiceProxySpec.scala
- Will refactor to move to standalone method
- Tests pending
> Quick fix for query parameter bug

- app/controllers/ReverseProxy.scala
- app/controllers/ServiceProxy.scala
- app/lib/Constants.scala
- app/lib/FlowAuth.scala
- test/lib/FlowAuthSpec.scala
- Idea is to log the request id every time we generate headers
from flow auth, so we can tie together in sumo
> Add request id into flow auth headers

- app/controllers/ReverseProxy.scala
- will let us keep request id from console, for example
> Preserve X-Flow-Request-Id if there

- app/controllers/ReverseProxy.scala
- app/controllers/ServiceProxy.scala
- currency and currency-internal map to same host - support this use
case and report the service name as currency,currency-internal
> Support multiple names / service host

- app/controllers/ServerProxy.scala
$ curl -d foo=bar http://localhost:7000/token-validations
[{"code":"validation_error","message":"Missing required field for type 'validation_form': 'token'"}]
> Validate all url form encoded requests

- app/controllers/ServerProxy.scala
- return 500 with proper error message
- including errorId for cross referencing
> Add global error handler

- app/controllers/ReverseProxy.scala
- app/controllers/ServerProxy.scala
- app/lib/ErrorHandler.scala
- app/lib/Errors.scala
- conf/base.conf
- add global error handler
- always return json
- standardize shape for system and client errors
> Improve error handling

- app/lib/LoggingUtil.scala
- test/lib/LoggingUtilSpec.scala
- Don't assume string even if only known use case
> Redact all js types properly

- app/controllers/ServerProxy.scala
- allows billing-internal to use billing context instead of default, for example
(cherry picked from commit 5b098482ce22bce064fb529b5adb52c7f5b77ebe)
> Better name resolution for contexts

- app/lib/Cloudwatch.scala
AmazonCloudWatchClient(AWSCredentials awsCredentials)
Deprecated.
use AwsClientBuilder.withCredentials(AWSCredentialsProvider) for example: AmazonCloudWatchClientBuilder.standard().withCredentials(new AWSStaticCredentialsProvider(awsCredentials)).build();
> Update constructor based on AWS Deprecation

- app/controllers/ReverseProxy.scala
> Revert "Additional check to make sure token is really for an org or partner"

- app/controllers/ServerProxy.scala
- app/lib/LoggingUtil.scala
- test/lib/LoggingUtilSpec.scala
- first step to potentially moving out to api builder validation library
- add tests
> Cleanup logging util a bit more. Add additional tests

- build.sbt
API Proxy Tests against http://localhost:7000
All tests Passed
> Upgrade apibuilder-validation

- app/lib/Route.scala
- scripts/helpers.rb
- scripts/test.rb
- will let proxy validate access to organizations resource
- still a work in progress
> Add new path to identify org

- build.sbt
- com.amazonaws
- aws-java-sdk-cloudwatch (1.11.217 => 1.11.220)
- commons-codec
- commons-codec (1.10 => 1.11)
> Upgrade libraries: com.amazonaws, commons-codec

- app/handlers/GenericHandler.scala
Use `.bodyAsSource` as the response may be streamed. Calling `.body` directly leads to blocking and waiting.
This should solve the `FlowError` issue reporting a `TimeoutException` after 50ms of blocking.
> Use bodyAsSource to avoid blocking when streaming the response

- app/handlers/GenericHandler.scala
> Revert "Use bodyAsSource to avoid blocking when streaming the response"

- conf/base.conf
Adding addition config as it appears to have worked to allow longer URI.
> Configure max uri length

- build.sbt
- com.amazonaws
- aws-java-sdk-cloudwatch (1.11.284 => 1.11.289)
- org.yaml
- snakeyaml (1.19 => 1.20)
> Upgrade libraries: com.amazonaws, org.yaml

- app/controllers/ReverseProxy.scala
- user copied  https://api.flow.io/:organization/catalog/items?limit=25&offset=0 url
from docs and was a bit confused why api key did not work - make this particular error clearer
> Improve error msg on :organization in URL

- app/lib/ProxyConfigFetcher.scala
Some return labels take a while to generate, even for returns
> return should default to 60 seconds

- build.sbt
- com.amazonaws
- aws-java-sdk-cloudwatch (1.11.342 => 1.11.348)
> Upgrade com.amazonaws.aws-java-sdk-cloudwatch

- app/lib/Authorization.scala
Intended to catch/resolve:
```
java.lang.UnsupportedOperationException: RS256 is an unknown or unimplemented JWT algo key
```
> Catch JWT token validation exception

- app/controllers/ReverseProxy.scala
To enhance user experience and integration, rather than throw an error if customer number is specified but does not exist, instead attempt to auth by session.
> [Returning Customers] Fallback

- app/controllers/ReverseProxy.scala
- Instead realy on the proxy config where routes are actually defined
- Solves a potential problem where these two are in conflict
> Remove apibuilder config from critical path of determining if a route is valid

- app/lib/ProxyConfigFetcher.scala
One minute isn't enough
Need to find another, better solution
> Revert "Allow MG to take up to a minute"

- build.sbt
- conf/base.conf
- project/plugins.sbt
Help us better understand resources on proxy instances ahead of FN full roll out and holiday 2019
> Enable metrics collection on proxy

- app/handlers/GenericHandler.scala
- app/lib/ErrorHandler.scala
- app/lib/ProxyRequest.scala
- app/lib/Util.scala
- test/lib/UtilSpec.scala
> Revert "Small code improvements (#434)"

- app/controllers/Internal.scala
- test/auth/AuthorizationParserSpec.scala
> Allow crawlers to load sessions

- app/controllers/Internal.scala
- app/controllers/RequestHandler.scala
- app/lib/CheckoutHealthcheck.scala
- Defines 'http://localhost:9000/_internal_/healthcheck/checkout' which will return ~82kb of text which is the
current payload size of our checkout
> Add checkout healthcheck

- .gitignore
- build.sbt
see: https://www.playframework.com/documentation/2.8.x/AkkaHttpServer#HTTP/2-support-(incubating)
> Add http2 support

- app/controllers/RequestHandler.scala
- app/controllers/ReverseProxy.scala
> Revert "Add operation names to traces"
