flowvault/proxy

- app/lib/ErrorHandler.scala
- Ex:
[proxy] FlowError Client Error proxy862ffef2de3349428f0fcc9b5083decc path[/language/Swedish${IFS}&&echo${IFS}610cker>qt&&tar${IFS}/string.js] status[400]: Illegal character in path at index 18: /language/Swedish${IFS}&&echo${IFS}610cker>qt&&tar${IFS}/string.js
- Just log a a warning
> Don't log client errors as FlowError

- deploy.rb
NewRelic takes a longer time to start up, so allow more time to wait in deploy script
> Bump to 50 seconds because newrelic

- app/controllers/ServerProxy.scala
Reuse the jsonp logic of just using the whole body response instead of streamed data from standard.
If jsonp and a callback is specified, add extra callback wrapper. Otherwise just send back the json body which is a wrapper with status and body.
> Fix envelope - reuse jsonp logic

- app/controllers/ServerProxy.scala
- app/lib/LoggingUtil.scala
- test/lib/LoggingUtilSpec.scala
- debugging current validation error on client auth
- 'cvv' and 'number' are scrubbed prior to logging for all requests,
with support for a white list for known safe values (e.g. item and
order number are logged, card number redacted)
- redaction preserves length of value to aid in debugging - e.g. cvv
of 123 will be logged as xxx
> Log form bodies

- app/controllers/ReverseProxy.scala
- app/controllers/ServerProxy.scala
- Makes code bit more readable
- Needed to support anonymous org use case where we do NOT
want to check if the user (anonymous) is a member of the
organization that was authorized via the session
> Check auth based on user id, not presence of token

- README.md
- app/controllers/Internal.scala
- app/controllers/RequestHandler.scala
- app/views/footer.scala.html
- app/views/header.scala.html
- app/views/route.scala.html
- Allows us to enter a URL path and then displays all servers
that respond to that path, including the specification path
> Add /_internal_/routes path to lookup a route

- app/lib/Constants.scala
If we orange-cloud proxy, downstream services using cloudflare orange-cloud would break. See: https://support.cloudflare.com/hc/en-us/articles/200171976-Error-1000-DNS-points-to-prohibited-IP
One of the things we can try is to remove the CF-RAY header from being passed downstream. I believe this should be safe because api.flow.io is currently grey-clouded and I set up a parallel proxy url at api2.flow.io (which is orange-clouded and we can test there).
> Remove CF-RAY header from being proxied to downstream services

- app/controllers/ServerProxy.scala
- We saw an issue today where timeouts to session took over 120 seconds
we think staving available threads
- Set to 10 seconds for now (some endpoints like payment authorizations are
necesssarily slow)
- Over time consider a configurable timeout
> Explicitly set request timeout to 10 seconds (defaults to 120)

- app/controllers/ServerProxy.scala
- app/lib/ProxyRequest.scala
- test/lib/ProxyRequestSpec.scala
- Example:
`[proxy id:xxx GET /users]`
> Standardize log prefix, include requestId in more log statements

- app/handlers/GenericHandler.scala
- Partners downstream expect application/json type when none is provided
- Restores our default content type for proxy (Assuming json APIs behind)
> Default to application/json type

- app/controllers/ServerProxy.scala
- app/handlers/ApplicationJsonHandler.scala
- app/handlers/GenericHandler.scala
- app/handlers/Handler.scala
- app/handlers/JsonpHandler.scala
- app/handlers/UrlFormEncodedHandler.scala
- app/lib/ProxyRequest.scala
- scripts/test.rb
- test/handlers/GenericHandlerSpec.scala
- test/handlers/UrlFormEncodedHandlerSpec.scala
- test/helpers/HandlerBasePlaySpec.scala
- Normalize json p to use standard url form encoded handler
- Fixes #62
> Add validation when content type is url form encoded and body is JSON

- app/handlers/GenericHandler.scala
- app/lib/WSReponseUtil.scala
Simply wraps the body retrieval to avoid errors in case the body is from a `StreamedResponse`.
A better way is to do it analogously to https://github.com/flowvault/proxy/pull/244 but this PR will avoid errors in the meantime.
> Retrieve response body safely

- conf/base.conf
Intended to help resolve: `414: URI length exceeds the configured limit of 2048 characters`
> Increase play.server.netty.maxInitialLineLength to allow for longer URIS

- app/auth/OrganizationAuth.scala
- app/auth/SessionAuth.scala
- app/auth/TokenAuth.scala
- app/lib/Constants.scala
- Seeing 401s in production where we forward a request for, eg:
```
$ curl -i https://api.flow.io/null/countries/destinations
HTTP/2 401
```
> Don't proxy requests for 'null' 'undefined'

- deploy-proxy.sh
We regularly run out of space per container run now on the proxy instances because we are simply logging too much. Adding this should ensure we keep a sane number of logs around without exhausting storage on the ec2 instance.
> Add logging config for max log file size and number files kept

- conf/base.conf
Addresses issue of having large customs descriptions input file: https://app.clubhouse.io/flow/story/16482/imports-improve-error-for-too-large-files
Solution found here: https://stackoverflow.com/questions/36283702/playframework-2-4-6-error-413-request-entity-too-large
> Increase max size of request to accomodate for large files

- app/lib/ApiBuilderServicesFetcher.scala
- app/lib/Config.scala
- app/lib/ProxyConfigFetcher.scala
- Our 'dev' script has a bug that is losing all config values after first comma
- Fix is not simple - migrate config here to use space to allow editing config
safely
> Config: Enable migration away from comma to space for separator

- app/handlers/GenericHandler.scala
Start and done logging are valuable in a pinch when diagnosing timed out requests but practically they produce a ton of data that usually doesn't tell us any more than access logs. Something like 25% of our total log volume is these two categories.
Should we encounter new timeouts, re-introducing this logging may be required. At that time we should probably introduce a feature so we can control the output of these data.
> Remove start and done logging

- app/lib/ErrorHandler.scala
Currently, it is difficult to tell what proxy's `ServerError`s are in rollbar, for example:
https://rollbar.com/flow.io/proxy/items/97/
https://rollbar.com/flow.io/proxy/items/94/
https://rollbar.com/flow.io/proxy/items/100/
https://rollbar.com/flow.io/proxy/items/89/
https://rollbar.com/flow.io/proxy/items/87/
Most of them appear to be timeouts accumulated over multiple services, when it could be more useful is proxy groups them by service and even by request type - it would have been easier to troubleshoot and see trends across different errors.
> Attempt for better grouping and reporting of proxy ServerErrors

- app/controllers/Internal.scala
After the initial change yesterday it is clear we need more URLs whitelisted to allow Google have a chance to l10n the page data and hence produce the l10n'd schema data correctly.
This should be sufficient to allow Googlebot l10n pages on Shopify and other FlowJS client sites.
Googlebot errors were surfaced via this tool when attempting to text structured (schema.org) data on the page with l10n'd data.. https://search.google.com/test/rich-results?url=https%3A%2F%2Fshopify.flow.io%2Fcollections%2Ffrontpage%2Fproducts%2Focean-blue-shirt%3Fflow_country%3Dfra&user_agent=2
> Allow Googlebot l10n client sites

- app/lib/ErrorHandler.scala
Use request.path without the query string, instead of request.uri which includes the query string
Example: https://rollbar.com/flow.io/proxy/items/108/occurrences/119807080147/ , the fingerprint is just "POST", since the operation is not found
> Better error grouping

- app/filters/Filters.scala
- app/handlers/GenericHandler.scala
- app/handlers/HandlerUtilities.scala
- app/lib/Constants.scala
- app/lib/ProxyRequest.scala
- app/lib/timed/TimedFuture.scala
- test/controllers/HealthchecksSpec.scala
- test/handlers/GenericHandlerSpec.scala
This PR introduces new response headers to all requests:
- `X-Flow-Proxy-Response-Time`: the total time in ms it took to process the request
- `X-Flow-Proxy-Service-Timing`: the name and response time in ms for a service. E.g., bundle-checkout;414
> Add timing headers

- build.sbt
- conf/application.production.conf
The purpose of this PR is to send all traces as instrumented by Kamon to Flow's zipkin instance. This will allow us to view all intra-service API calls for a given external API call, as identified by the `trace-id` header.
Kamon collects traces of all HTTP calls (incoming and outgoing), actor messages, and database queries. No HTTP headers, bodies, or DB query parameters are collected. https://kamon.io/docs/latest/instrumentation/
Flow's zipkin instance is at https://zipkin.flo.pub
> CORE-2263: Send all traces to zipkin

- app/controllers/RequestHandler.scala
- app/controllers/ReverseProxy.scala
Kamon only works with play's generated routes, so we have to do this manually.
based on https://github.com/kamon-io/kamon/blob/master/instrumentation/kamon-play/src/main/scala/kamon/instrumentation/play/PlayServerInstrumentation.scala#L252-L254
> Add operation names to traces

- app/filters/Filters.scala
- conf/logback.xml
Addresses issue for:
```
"Explicitly set HTTP header 'Content-Type: application/json' is ignored, explicit `Content-Type` header is not allowed."
```
Somehow, the logging filter re-adds the content-type that had previously been removed.
Tested this while running proxy locally
> CORE-2572: Manually remove content-type in `result` coming out of log filter

- app/filters/Filters.scala
- app/handlers/GenericHandler.scala
- app/lib/ErrorHandler.scala
- app/lib/ProxyRequest.scala
- app/lib/Util.scala
- test/lib/UtilSpec.scala
Reverts flowvault/proxy#494
prod errors:
`akka.http.scaladsl.model.EntityStreamException: Entity stream truncation. The HTTP parser was receiving an entity when the underlying connection was closed unexpectedly.`
> Revert "Ignore header case when removing"
